// Dummy data standing in for `problem_statement` API rows until the
// backend is wired up. Shape mirrors what the real endpoint should return.

export const DUMMY_PROBLEMS = [
  {
    id: "P001",
    category: "water",
    priority: "critical",
    title: "Contaminated Groundwater in Namkum Block",
    description:
      "Multiple tube wells in Namkum block have been showing elevated fluoride and arsenic levels since June 2024. Residents report skin issues and are relying on costly private water tankers.",
    location: "Namkum, Ranchi",
    stage: 3,
    stageMeta: "University Working",
    affected: 8400,
    voices: 1280,
    institutions: ["BIT", "NIT"],
    reportedByMe: true,
    following: false,
    lastUpdate: "2 Sept",
  },
  {
    id: "P002",
    category: "agriculture",
    priority: "high",
    title: "Lack of Cold Storage for Potato Farmers in Khunti",
    description:
      "Potato farmers in Khunti district lose 30–40% of their produce annually due to lack of affordable cold storage. The nearest facility is over 60km away, making transport costly and impractical.",
    location: "Khunti, Jharkhand",
    stage: 4,
    stageMeta: "Prototype",
    affected: 3200,
    voices: 620,
    institutions: ["XISS"],
    reportedByMe: false,
    following: true,
    lastUpdate: "29 Aug",
  },
  {
    id: "P003",
    category: "healthcare",
    priority: "critical",
    title: "Shortage of Specialist Doctors at Sadar Hospital, Lohardaga",
    description:
      "Sadar Hospital in Lohardaga has been operating without a cardiologist and neurologist for 18 months. Patients travel 150 km to Ranchi for basic specialist consultations.",
    location: "Lohardaga, Jharkhand",
    stage: 5,
    stageMeta: "Pilot",
    affected: 52000,
    voices: 3100,
    institutions: ["RIMS"],
    reportedByMe: false,
    following: true,
    lastUpdate: "1 Sept",
  },
  {
    id: "P004",
    category: "infrastructure",
    priority: "high",
    title: "Broken Road Connectivity — Torpa to Karjo",
    description:
      "18 km stretch of road between Torpa and Karjo has been damaged since the 2023 monsoon. School buses cannot ply the route, forcing children to walk over 5 km daily.",
    location: "Torpa, Khunti",
    stage: 2,
    stageMeta: "Validated",
    affected: 6800,
    voices: 2200,
    institutions: ["BIT"],
    reportedByMe: false,
    following: false,
    lastUpdate: "27 Aug",
  },
  {
    id: "P005",
    category: "education",
    priority: "high",
    title: "High Dropout Rate in Girls' Schools — Simdega",
    description:
      "Government data shows 38% dropout rate for girls after Class 8 in Simdega block. Root causes include distance to school, early marriage pressure and lack of sanitation facilities.",
    location: "Simdega, Jharkhand",
    stage: 3,
    stageMeta: "University Working",
    affected: 4100,
    voices: 1850,
    institutions: ["CUJ"],
    reportedByMe: false,
    following: false,
    lastUpdate: "30 Aug",
  },
  {
    id: "P006",
    category: "environment",
    priority: "medium",
    title: "Forest Fire Risk — Palamu Tiger Reserve Buffer",
    description:
      "Uncontrolled forest fires in the Palamu buffer zone have destroyed 4,000+ hectares in 3 years. Satellite data shows early fire indicators going unmonitored during dry months.",
    location: "Palamu, Jharkhand",
    stage: 1,
    stageMeta: "Reported",
    affected: 12000,
    voices: 480,
    institutions: [],
    reportedByMe: false,
    following: false,
    lastUpdate: "25 Aug",
  },
];

export const DUMMY_USER = {
  name: "Ravi Kumar Mahto",
  firstName: "Ravi",
  avatarInitial: "R",
  village: "Namkum",
  block: "Namkum",
  district: "Ranchi",
  state: "Jharkhand",
  pincode: "834010",
  address: "HIG-24, Harmu Housing Colony",
  phone: "+91 94310 58721",
  email: "ravikumar.mahto@gmail.com",
  language: "Hindi",
  memberSince: "June 2024",
};