import enum

from sqlalchemy import (
    ARRAY,
    JSON,
    BigInteger,
    Boolean,
    CHAR,
    CheckConstraint,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Identity,
    Integer,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ENUM, JSONB, UUID
from sqlalchemy.orm import declarative_base, relationship

Base = declarative_base()


class ProblemStatus(enum.Enum):
    NO_BIDDERS = "NO_BIDDERS"
    ASSIGNED = "ASSIGNED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    CLOSED = "CLOSED"


class UserRole(enum.Enum):
    ADMIN = "ADMIN"
    USER = "USER"
    SPOC = "SPOC"
    TEAM_LEAD = "TEAM_LEAD"


class University(Base):
    __tablename__ = "universities"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    # GENERATED BY DEFAULT so we can seed it from spoc_universities.serial_id.
    # Do NOT change to always=True.
    token = Column(BigInteger, Identity(always=False), unique=True, nullable=False)
    name = Column(Text, nullable=False)


class Workspace(Base):
    __tablename__ = "workspaces"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    serial_id = Column(BigInteger, Identity(always=True), unique=True, nullable=False)
    milestones = Column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )
    cost_estimate = Column(Numeric, nullable=False)
    industry_partner = Column(UUID(as_uuid=True), nullable=True)


class SpocUniversity(Base):
    __tablename__ = "spoc_universities"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    serial_id = Column(BigInteger, Identity(always=True), unique=True, nullable=False)
    uni_name = Column(Text, nullable=False)
    name = Column(Text, nullable=False)
    subject_expertise = Column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )
    problems_proposal = Column(
        JSONB, nullable=False, server_default=text("'[]'::jsonb")
    )
    phone_number = Column(Text, nullable=False)
    pass_hash = Column(Text, nullable=False)

    __table_args__ = (
        CheckConstraint(
            "phone_number ~ '^[0-9]{10}$'",
            name="spoc_universities_phone_number_check",
        ),
    )


class TeamLead(Base):
    __tablename__ = "team_leads"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    serial_id = Column(BigInteger, Identity(always=True), unique=True, nullable=False)

    name = Column(Text, nullable=False)
    email = Column(Text, nullable=False, unique=True, index=True)
    pass_hash = Column(Text, nullable=False)
    token = Column(BigInteger, nullable=False, unique=True)

    workspace_id = Column(
        UUID(as_uuid=True), ForeignKey("workspaces.id"), nullable=False
    )
    uni_id = Column(
        UUID(as_uuid=True), ForeignKey("spoc_universities.id"), nullable=False
    )

    team_members = Column(
        ARRAY(Text), nullable=False, server_default=text("'{}'::text[]")
    )

    workspace = relationship("Workspace")
    university = relationship("SpocUniversity")

    # 1:1 reverse side (FK is owned by ProblemStatement.assigned_to)
    problem = relationship(
        "ProblemStatement",
        uselist=False,
        back_populates="assigned_team_lead",
    )


class Citizen(Base):
    __tablename__ = "citizens"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    serial_id = Column(BigInteger, Identity(always=True), unique=True, nullable=False)
    name = Column(Text, nullable=False)
    phone_number = Column(Text, nullable=False)
    pass_hash = Column(Text, nullable=True)
    location = Column(Text, nullable=False)
    occupation = Column(Text, nullable=False)
    age = Column(Integer, nullable=False)
    gender = Column(CHAR(1), nullable=False)
    university_token = Column(
        BigInteger, ForeignKey("universities.token"), nullable=True
    )
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    university = relationship("University")

    __table_args__ = (
        CheckConstraint(
            "occupation = lower(occupation) AND occupation !~ '\\s'",
            name="citizens_occupation_check",
        ),
        CheckConstraint("age > 0 AND age < 130", name="citizens_age_check"),
        CheckConstraint(
            "gender = ANY (ARRAY['M'::bpchar, 'F'::bpchar])",
            name="citizens_gender_check",
        ),
    )


class ProblemStatement(Base):
    __tablename__ = "problem_statements"

    id = Column(
        UUID(as_uuid=True), primary_key=True, server_default=text("gen_random_uuid()")
    )
    token_number = Column(
        BigInteger, Identity(always=True), unique=True, nullable=False
    )
    user_id = Column(UUID(as_uuid=True), nullable=False)
    title = Column(Text, nullable=False)
    pd = Column(Text, nullable=False)
    photos = Column(ARRAY(Text), server_default=text("'{}'::text[]"))
    videos = Column(ARRAY(Text), server_default=text("'{}'::text[]"))
    location = Column(Text, nullable=False)
    status = Column(
        ENUM(ProblemStatus, name="problem_status"),
        nullable=False,
        server_default=text("'NO_BIDDERS'::problem_status"),
    )
    assigned_to = Column(
        UUID(as_uuid=True),
        ForeignKey("team_leads.id"),
        nullable=True,
        unique=True,  # enforces 1:1
    )
    proposals = Column(JSONB, nullable=False, server_default=text("'[]'::jsonb"))
    date_reported = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    categories = Column(ARRAY(Text), server_default=text("'{}'::text[]"))
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    assigned_team_lead = relationship("TeamLead", back_populates="problem")

    __table_args__ = (
        CheckConstraint(
            "jsonb_typeof(proposals) = 'array'",
            name="problem_statements_proposals_check",
        ),
    )


class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True)
    name = Column(String, nullable=False)
    email = Column(String, nullable=False)
    phone = Column(String, nullable=True)
    password_hash = Column(String, nullable=False)
    role = Column(ENUM(UserRole, name="role"), nullable=False)
    is_active = Column(Boolean, nullable=False)
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class AiProblemTest(Base):
    __tablename__ = "ai_problem_tests"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String, nullable=False)
    description = Column(Text, nullable=False)
    location = Column(String, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    citizens_affected = Column(Integer, nullable=False)
    predicted_category = Column(String, nullable=True)
    predicted_categories = Column(JSON, nullable=True)
    category_needs_review = Column(Boolean, nullable=True)
    priority_score = Column(Integer, nullable=True)
    priority_label = Column(String, nullable=True)
    priority_reasons = Column(JSON, nullable=True)


class RefreshToken(Base):
    __tablename__ = "refresh_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)  # no FK
    role = Column(
        Text, nullable=False
    )  # "citizen" | "spocuni" | "teamlead" | "ADMIN" | ...
    token_hash = Column(String, nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    revoked = Column(Boolean, nullable=False, default=False)
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
